### PR TITLE
adding new pages

### PR DESCRIPTION
**Pull request by frankstepanski**
@chrisfyi @AidanWeb 

Just added some pages and little stuff.

### CODE REVIEW

**Comment by AidanWeb** [comment]
I approve!

**Comment by chrisfyi** [comment]
It says there are some conflicts here that need to be resolved before we merge

**Comment by AidanWeb** [comment]
> It says there are some conflicts here that need to be resolved before we merge

Yeah I think that if @frankstepanski the `dist/main.js `and `dist/main.js.map` files to his `.gitignore` then he can push to his branch again and it will no longer have the conflict. Since we're building our dist files every time we make a front-end change, having them in `.gitignore` shouldn't cause us any problems

**Comment by AidanWeb** [comment]
Closing per conversation with Frank

**Pull request closed without merging**
